<?php

namespace App\Repository;

use App\Entities\Properties;
use Bootstrap\Doctrine;

/**
 * PropertiesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PropertiesRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param $data
     * @return array
     */
    public static function updatePropertyDetails($data): array
    {
        $em = Doctrine::getEntityManager();
        $propertiesRepository = $em->getRepository('bookingportal:Properties');

        $properties = new Properties();
        $properties->setEmail($data['email']);
        $properties->setName($data['name']);
        $properties->setSize($data['size']);
        $properties->setType($data['type']);
        $properties->setDescription($data['description']);
        $properties->setAddress($data['address']);
        $properties->setLongitude($data['longitude']);
        $properties->setLattitude($data['latitude']);
        $properties->setStatus(true);
        $properties->setCreatedDate(time());

            $em->persist($properties);
            $em->flush();

            return [
                'success' => 'true',
                'email' => $data['email']

            ];
        try {

        }

        catch (\Throwable $exception) {

            return [
                'success' =>false,
                'message' => 'OOPS! Something went wrong please try again later'
            ];
        }
    }

    /**
     * @param $email
     * @return array
     */
    public static function getPropertyDetails($email): array
    {
        $em = Doctrine::getEntityManager();

        return $em->getRepository('bookingportal:Properties')->findBy(['email' => $email]);
    }
}
